# .travis.yml
# This file should be at the root of your project
language: ruby
cache: bundler
before_install:
  - gem install -v 1.16.6 bundler --no-rdoc --no-ri
script:
  - bundle exec jekyll build
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
